# -*- coding: utf-8 -*-
"""IMDB Top Movies.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mbwnqBLoXmGdMj88tpj0nke9T_FKrL2_
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd

url = "https://www.imdb.com/chart/top/"

page = requests.get(url)
page

## display the page source code
# page.content

soup = BeautifulSoup(page.content, "html.parser")
#print(soup.prettify())

# scrap movie names
scraped_movies = soup.find_all('td', class_='titleColumn')
scraped_movies

# parse movie names
movies = []
for movie in scraped_movies:
    movie = movie.get_text().replace('\n', "")
    movie = movie.strip(" ")
    movies.append(movie)
movies

# scrap rating for movies
scraped_ratings = soup.find_all('td', class_='ratingColumn imdbRating')
scraped_ratings

# parse ratings
ratings = []
for rating in scraped_ratings:
    rating = rating.get_text().replace('\n', '')
    ratings.append(rating)
ratings

"""**Store the Scraped Data**"""

data = pd.DataFrame()
data['Movie Names'] = movies
data['Ratings'] = ratings
data.head()

data.to_csv('IMDB Top Movies.csv', index=False)